config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "articles#index"

  # define other routes below
  resources :articles do 
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible #include the concern
    # add relationship with the Article's records
    has_many :comments,dependent: :destroy
    # add validators below
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible #include concern
  belongs_to :article
  # add validators below
  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
      status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # add authentication control
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all()
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params())

    if @article.save()
      redirect_to(@article)
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params())
      redirect_to(@article)
    else
      redirect_to(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @article = Article.find(params[:id])
    puts(@article)
    @article.destroy()
    redirect_to(root_path,status: :see_other)
  end

  private 
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comments_params)
        redirect_to(article_path(@article))
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy()
        redirect_to(article_path(@article),status: 303)
    end

    private
        def comments_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/page2_controller.rb
class Page2Controller < ApplicationController
  def Index
  end

  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/page_index_controller.rb
class PageIndexController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page2_helper.rb
module Page2Helper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/page_index_helper.rb
module PageIndexHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message  %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>  

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<hr>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1> Articles </h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
    <% @articles.each do |article | %>
        <% unless article.archived? %>
           <li>
                <%= link_to(article.title,article) %>
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %> 

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<hr>
<p><%= @article.body %></p>
<%= link_to "Edit", edit_article_path(@article) %> | <%= link_to "Destroy", article_path(@article), data: {turbo_method: :delete,
    turbo_confirm: "Are you sure?"
} %>
<h2>Comments</h2>
<hr>
<%= render @article.comments %>

<%# the add comment form is below %>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
        <%= link_to "Destroy Comment", [comment.article, comment], data: {
            turbo_method: :delete,
            turbo_confirm: "Do you want to delete this comment?"
        }%>
    </p>
<% end %>

app/views/comments/_form.html.erb
<h2>Add Comment</h2>
<hr>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    <p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/comments/index.html.erb
<h1>Comments Heading</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/page2/Index.html.erb
<h1>Page2#Index</h1>
<p>Find me in app/views/page2/Index.html.erb</p>

app/views/page2/index.html.erb
<h1>Page2#index</h1>
<p>Find me in app/views/page2/index.html.erb</p>

app/views/page_index/index.html.erb
<h1>PageIndex#index</h1>
<p>Find me in app/views/page_index/index.html.erb</p>